name: mac.com
favicon: null
layout_spectrum: 0.33214412606321275
typography_spectrum: 0.6232800949364901
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7532741681206971
  lightness: 0.5462942577432841
  saturation: 0.6339685404673219
  rhythmicContrast: 0.3933688150718808
purpose: []
